import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Providers } from './providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

function Container({ children, }: { children: React.ReactNode }) {
  return (
    <div className='content-center flex place-items-center m-auto w-6/12 p-2' >
      { children }
    </div>
  )
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* <body className={inter.className}>{children}</body> */}
      <Providers>
        <Container>
          { children }
        </Container>
      </Providers>
    </html>
  )
}
